const themes = {
  primary: {
    spacing: {
      small: "0.3em",
      primary: "0.8em",
      half: "0.5em",
      logosGap: "1.18em",
      septenary: "1.3em",
      tertiary: "2em",
      logo: "13em",
      headerNavVertical: "2em",
      headerNavVerticalTablet: "2em",
      adminWithinBlocks: "3em",
      headerNavHorizontal: "5em",
      topButtonSpace: "4.5em",
      btnHeight: "7em",
      btnWidth: "16em",
      aboutUsCard: "30%",
      aboutUsCardMobile: "22em",
      aboutUsDescription: "8em",
      cardPartners: "14em",
      btwLogoAndMenu: "8.5em",
      servicesGlobalMarginBetweenBlocks: "12.5em",
      servicesMarginBetweenBlocks: "11.7em",
      servicesMarginBetweenBlocksTablet: "8em",
      servicesMarginBetweenBlocksMobile: "4em",
      servicesMarginBetweenFooter: "10.3em",
      servicesMarginBetweenFooterTablet: "6.5em",
      servicesMarginBetweenFooterMobile: "5.8em",
    },
    font: {
      family: {
        barlow: "'Barlow', sans-serif",
        sourceCode: "'Source Code Pro', monospace",
        mulish: "'Roboto', sans-serif",
        gilroy: "'Gilroy', sans-serif",
        namu: "'NAMU', sans-serif",
        openSans: "'Open Sans', sans-serif",
        inter: "'Inter', sans-serif",
        pressStart: "'Press Start 2P', cursive",
      },
      weight: {
        light: 300,
        normal: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
        extraBold: 800,
        heavy: 900,
      },
      size: {
        careersTitle: "6.1em",
        smallerCareersTitle: "4em",
        reviewSmallText: "1.03em",
        homeFooterButton: "0.285em",
        hexadecimal: "0.375em",
        septenary: "0.6em",
        quinary: "0.72em",
        fourteenth: "0.875em",
        articleViews: "1.17em",
        vistaco: "1.1em",
        tertiary: "1.2em",
        primary: "1em",
        aboutUsBelieveText: "1.35em",
        aboutUsCardText: "1.3em",
        linkText: "1.4em",
        oneAndHalf: "1.5em",
        buttonText: "1.5em",
        articleSubtitle: "1.6em",
        menuElement: "1.7em",
        adminMenuElement: "0.8em",
        articleTagDescription: "1.8em",
        feedbackName: "1.83em",
        careersFormLaptop: "1.3em",
        adminButton: "1.8em",
        faqQuestion: "1.669em",
        articleDesktopTag: "1.335em",
        faqAnswer: "1.335em",
        oneAndNine: "1.9em",
        secondary: "2em",
        blogArticleTitle: "2.2em",
        quaternary: "2.6em",
        articleDescription: "3.15em",
        smallAboutSubtitle: "2.7em",
        aboutUsSubtitle: "3.35em",
        mainPagePhoto: "2.68em",
        ourWorkText: "3.61vw",
        ourWorkTextBig: "3.5em",
        reviewTitle: "2.5em",
        reviewText: "1.334em",
        projectLink: "1.165em",
        articleTitle: "5em",
        articleTitleMob: "32px",
        bigTitle: "4.125em",
        headerLinkText: "1.3em",
        authorDate: "0.83em",
        mainBlogTitle: "2.83em",
        mainBlogDescription: "18px",
        mainBlogAuthor: "14px",
        imageDescription: "12px",
        smallestBlogTitle: "14px",
        smallBlogTitle: "21px",
        smallPortfolioText: "22px",
        smallBlogDescription: "14px",
        h5BlogTitle: "18px",
        mediumArticleTitle: "27px",
        semiMediumArticleTitle: "24px",
        secondaryArticleTitle: "30px",
        portfolioCTATitle: "40px",
        secondaryArticleDescription: "20px",
        secondaryArticleAuthor: "16px",
        articleContentText: "16px",
        articleDate768: "18px",
        articleTabletTitle: "42px",
        article4KH3Title: "36px",
        secondaryServicesTitle: "3.33em",
        secondaryServicesSubTitle: "2.67em",
        secondaryServicesText: "1.225em",
        email: "16px",
        homeHeader: "8.334em",
        homeHeaderTablet: "8.15em",
        homeHeaderPc: "8.2em",
        homeHeaderPcHd: "6.945em",
        homeSubtitle: "6.2em",
        homeSmallTitle: "5.6em",
        homeCardSubtitle: "5.68em",
        serviceTitle: "5.5em",
        serviceSubtitle: "2.5em",
        tabletServiceTitle: "4em",
        homeMainSubtitle: "2.167em",
        inBlockMaxTableText: "1.3em",
        faqMobileTitle: "3em",
        portfolioMobile: "3.8em",
        notFoundPageTitlePc: "2.8em",
        notFoundPageTitleTablet: "1.8em",
        webAuditSubtitle: "3.33em",
        webAuditSubtitlePC: "3.5em",
        webAuditSubtitleTabletLandscape: "2.5em",
        webAuditSubtitleTabletPortrait: "2.2em",
        webAuditSubtitleMobile: "2.3em",
        estimationFormRegular: "1.32em",
        estimationFormMedium: "0.9em",
      },
    },
    colors: {
      transparent: "transparent",
      mainGradientColor1: "#89A3D1",
      mainGradientColor2: "#C7ECC0",
      homePageGradient1: "#D7DDFF",
      homePageGradient2: "#ABB5F9",
      portfolioGradient1: "#D7DCFF",
      portfolioGradient2: "#6C7BDC",
      infiniteTextGradientColor1: "#d6ffbb",
      infiniteTextGradientColor2: "#5869dd",
      infiniteTextColor1: "#d7dcff",
      infiniteTextColor2: "#6c7bdc",
      darkGrey: "#8F8E93",
      testimonialBorder: "#C0BFC0",
      headerBorder: "#8F8E93",
      headerBorderHover: "#F2EA86",
      attachmentIcon: "#5869DD",
      chatFormColor: "#8F8E93",
      chatMessageBgc: "#DDDCDB",
      chatSendedMessageBgc: "#D2D4EA",
      gray: "#535353",
      cyanBlue: "#0070f3",
      lightGray: "#E5E5E5",
      separator: "#CDCDCD",
      decorationText: "#C7FB9C",
      quinary: "#FFA046",
      primary: "#000",
      grey: "#f1efed",
      secondary: "#fff",
      starActive: "#FBA446",
      starDisable: "#EEE6DD",
      previewArticleText: "#BDC4FA",
      septenary: "#A9CDF5",
      blue: "#85BEFD",
      linkBlue: "#3C95F9",
      darkBlue: "#5869DD",
      darkPurple: "#3c4796",
      greyContactStep: "#6a6b70",
      hoverBlue: "#2E3773",
      calculatorDarkBlue: "#4654B1",
      adminBlue: "#095AF8",
      tagBg: "#3749C5",
      hoveredBlogTag: "#3749C5",
      cardDarkGreen: "#90e645",
      orange: "#FFC061",
      green: "#B6FD7A",
      lightBlue: "#436C9B",
      lighten: {
        blue: "#A6D0FF",
        orange: "#FFCE85",
        green: "#CAFF9D",
      },
      lightShadows: "lightgray",
      errorText: "#ea0000",
      adminRed: "#F80909",
      grayBack: "#EFEEEE",
      comment: "#8F8E93",
      dropdownBorder: "rgba(143,142,147,0.5)",
      darkedGrayBack: "#DDDBDB",
      deleteButton: "#F80909",
      feedbackRole: "#A9CDF5",
      black: "#000",
      authorGrey: "#716D6D",
      darkBlueBlockchain: "#392770",
      blogDarkText: "#272C2F",
      blogArticleText: "#535557",
      blogBackground: "#f1efed",
      blogFooter: "#EBE9EB",
      blogDropdownHover: "#F8F7F5",
      chatContainerBgc: "#F1EFED",
      careerBackground: "#f1efed",
      validationErrorText: "#F80909",
      portfolioBg: "#F1EFED",
      estimationAdminBg: "#F1EFED",
      portfolioHover: "#F2EA86",
      faqBorder: "#B5B5B5",
      bigDigit: "#F0EFED",
      lightGreyBorder: "#D9D9D9",
      inputGrey: "#787877",
      ourWork: "#A7A6A9",
      serviceHighlight: "#BABABA",
      deleteImageHover: "#ad1313",
      adminInputBorder: "#A9A5A4",
      whatsApp: "#4DA303",
      telegram: "#34AADF",
      calculatorButtonBorderBg: "#b2b2b2",
      calculatorButtonBg: "#e7e5e3",
      calculatorHorizontalLine: "#C6C6C6",
      calculatorEmailPlaceholder: "#797877",
      modalFormBackground: "rgba(241, 239, 237, 0.7)",
      careersPlaceholder: "rgba(0, 0, 0, 0.5)",
      bottomBorderEstimationForm: "rgba(241, 239, 237, 0.5)",
      modalWrapperEstimationForm: "rgba(241, 239, 237, 0.8)",
      loaderSpinner: "#8f8e93",
      borderRateCard: "#c0bfc0",
      gradientColor1RateCard: "#d6ffbb4d",
      gradientColor2RateCard: "#5869dd4d",
      mutedBlueGrey: "#6A6B70",
      jetBlack: "#000000",
      caseStudyTagGradientDark: "rgba(221, 221, 221, 0.22)",
      caseStudyImpactCardCountBlock: "#535557",
      gradientColorTransparent1: "rgba(214, 255, 187, 0.3)",
      gradientColorTransparent2: "rgba(88, 105, 221, 0.3)",
      gradientColorCountLabel1: "rgba(199, 236, 192, 0.5)",
      gradientColorCountLabel2: "rgba(137, 163, 209, 0.5)",
      gradientGrey: "#DDDDDD27",
      vodka: "#C3C9F3",
      greyAdminServices: "#CAC9C7",
      servicesBackground: "#e5e5ec",
      dropdownHover: "#E5E3E1",
      aiSolutionsGradient1: "#D0D5F5",
      aiSolutionsGradient2: "#BBC1EB",
      celeste: "#D0D1C9",
      emperor: "#525252",
      cloud: "#CAC9C7",
      dividerHover: "#8D99E8",
    },
    media: {
      minBreakpoint360: "(min-width: 360px)",
      maxLowestScreenMobile: "(max-width: 374px)",
      minLowestScreenMobile: "(min-width: 374px)",
      maxWidth410: "(max-width: 410px)",
      maxBreakpoint424: "(max-width: 424px)",
      minBreakpoint424: "(min-width: 424px)",
      min455: "(min-width: 455px)",
      minLowScreenMobile: "(min-width: 474px)",
      maxLowScreenMobile: "(max-width: 474px)",
      minMobilePortrait: "(min-width: 550px)",
      maxMobilePortrait: "(max-width: 550px)",
      minBreakpoint560: "(min-width: 560px)",
      maxBreakpoint560: "(max-width: 560px)",
      estiomationFormWidth: "(max-width: 570px)",
      minEstiomationFormWidth: "(min-width: 570px)",
      maxLowMobileHeight: "(max-height: 610px)",
      max737: "(max-width: 737px)",
      minTablet: "(max-width: 625px)",
      maxTablet: "(min-width: 625px)",
      max640: "(max-width: 640px)",
      minMobileHeight: "(min-height: 710px)",
      maxMobileHeight: "(max-height: 710px)",
      minMobileWidth: "(min-width: 710px)",
      maxMobileWidth: "(max-width: 710px)",
      max762: "(max-width: 762px)",
      min762: "(min-width: 762px)",
      min767Mobile: "(min-width: 767px)",
      max767Mobile: "(max-width: 767px)",
      maxMobile: "(max-width: 768px)",
      min768Mobile: "(min-width: 768px)",
      minMobile: "(min-width: 769px)",
      minTabletPortrait: "(min-width: 769px)",
      maxMiniTabletLandScape: "(max-width: 840px)",
      minMiniTabletLandScape: "(min-width: 840px)",
      minTabletLandScape: "(min-width: 992px)",
      maxTabletPortrait: "(max-width: 992px)",
      minBreakpoint1000: "(min-width: 1000px)",
      maxBreakpoint1000: "(max-width: 1000px)",
      minBreakpoint1100: "(min-width: 1100px)",
      maxBreakpoint1100: "(max-width: 1100px)",
      max1199: "(max-width: 1199px)",
      minLaptop: "(min-width: 1200px)",
      maxTabletLandScape: "(max-width: 1200px)",
      minBreakpoint1250: "(min-width: 1250px)",
      maxBreakpoint1250: "(max-width: 1250px)",
      minService: "(min-width: 1300px)",
      maxService: "(max-width: 1300px)",
      minServiceWeb: "(min-width: 1400px)",
      maxServiceWeb: "(max-width: 1400px)",
      min1440: "(min-width: 1440px)",
      max1440: "(max-width: 1440px)",
      maxServiceMobile: "(max-width: 1425px)",
      minPC: "(min-width: 1500px)",
      maxLaptop: "(max-width: 1500px)",
      minBreakpoint1600: "(min-width: 1600px)",
      maxBreakpoint1600: "(max-width: 1600px)",
      minPCFullHD: "(min-width: 1800px)",
      maxPCFullHD: "(max-width: 1800px)",
      min4K: "(min-width: 1920px)",
      maxLaptopL: "(max-width: 1920px)",
      minWidth2200: "(min-width: 2200px)",
      minWidth2500: "(min-width: 2500px)",
      minPCTwoThousand: "(min-width: 2560px)",
      maxPCTwoThousand: "(max-width: 2560px)",
      minPCFourThousand: "(min-width: 3840px)",
      maxPCFourThousand: "(max-width: 3840px)",
      onlyTabletPortrait: "(min-width: 769px) and (max-width: 992px)",
      minTabletPortraitToMaxTabletLandScape:
        "(min-width: 769px) and (max-width: 1200px)",
      onlyTabletLandScape: "(min-width: 992px) and (max-width: 1200px)",
      onlyLaptop: "(min-width: 1200px) and (max-width: 1500px)",
      onlyLaptopL: "(min-width: 1440px) and (max-width: 1920px)",
      onlyPC: "(min-width: 1500px) and (max-width: 1800px)",
      onlyTablet: "(min-width: 768px) and (max-width: 1100px)",
    },
  },
} as const;

export default themes;
