name: Continuous Integration Staging

on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-landing:
    name: Build landing dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build landing Dockerfile
        run: cd landing && docker build -f Dockerfile.staging .
